### ISSUE TITLE
channel-transport-reaction triggers assertion in fenics-adapter

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/tutorials#374]
- Tutorials state (last commit / release): https://github.com/precice/tutorials/pull/333/commits/ebf6c36f9b60f33cc7c421e5be47fef79efbeef7
- Versions of solvers and adapters used: https://github.com/precice/fenics-adapter/pull/153/commits/2ae1de54cdcc2a514d62ebf3cc69d4449b82c82e
- preCICE version: https://github.com/precice/precice/commit/e1e20f9d6cfb64f1965e27a959a7553ceaea7cdc and https://github.com/precice/python-bindings/tree/v3.0.0.0dev2

The following assertion is triggeres by `channel-transport-reaction`:

```
tutorials/channel-transport-reaction/fluid-fenics$ ./run.sh 
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
---[precice]  This is preCICE version 3.0.0
---[precice]  Revision info: v2.5.0-461-ge1e20f9d6
---[precice]  Build type: Debug
---[precice]  Configuring preCICE with configuration "/home/benjamin/Programming/tutorials/channel-transport-reaction/fluid-fenics/../precice-config.xml"
---[precice]  I am participant "Flow"
Participant Flow is write-only participant
Traceback (most recent call last):
  File "fluid.py", line 121, in <module>
    precice.initialize(coupling_subdomain=CouplingDomain(), write_object=u_)
  File "/home/benjamin/.local/lib/python3.8/site-packages/fenicsprecice/fenicsprecice.py", line 419, in initialize
    vertices = get_coupling_triangles(function_space, coupling_subdomain, fenics_edge_ids, id_mapping)
  File "/home/benjamin/.local/lib/python3.8/site-packages/fenicsprecice/adapter_core.py", line 439, in get_coupling_triangles
    assert (v2 != v2)
AssertionError
---[precice]  Implicitly finalizing in destructor
```

Since I'm not familiar with this tutorial, I will document this issue for now in favor of merging #333. Any help here would be appreciated. First starting point would be to check whether this tutorial actually works on the latest distribution release.

**Comment by BenjaminRodenberg** [comment]
The assertion is obviously wrong, but the function is also not tested in the adapter. This makes it basically an issue of the adapter that we also have to fix over there. Cannot evaluate the tutorial, but for now I will assume that it is working. Let's keep this issue open until the problem in the adapter is fixed.

**Comment by BenjaminRodenberg** [comment]
The partitioned heat equation actually runs into the same problem. This was just hidden by the way how the `run.sh` was set up. Changed this, see https://github.com/precice/tutorials/commit/5d22b7601d895fa2da1977f41c70f5e59313c1ef.

**Comment by MakisH** [comment]
The channel-transport-reaction is known to work fine since a while and it is now integrated in the system tests. I assume there is nothing else to do here.
