### ISSUE TITLE
Nutils participant crash causes systemtest failure

### ISSUE THREAD

**Issue by Eder-K** [precice/tutorials#53]
The systemtest for nutils-of has [stopped working recently](https://travis-ci.org/precice/systemtests/builds/605812235). In the highlighted line 756 of [this job log](https://travis-ci.org/precice/systemtests/jobs/605812258#L756) we can see that the Nutils participant launches the [cht.py](https://github.com/precice/tutorials/blob/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils/Nutils/cht.py) script from the Nutils tutorial and subsequently errors:
```
Attaching to nutils-adapter
nutils-adapter | Traceback (most recent call last):
nutils-adapter |   File "cht.py", line 3, in <module>
nutils-adapter |     import nutils, numpy, treelog
nutils-adapter |   File "/home/[secure]/nutils/nutils/__init__.py", line 37, in <module>
nutils-adapter |     from . import numeric, element, function, expression, mesh, topology, util, \
nutils-adapter |   File "/home/[secure]/nutils/nutils/element.py", line 31, in <module>
nutils-adapter |     from . import util, numpy, numeric, cache, transform, warnings, types, points, _
nutils-adapter |   File "/home/[secure]/nutils/nutils/cache.py", line 25, in <module>
nutils-adapter |     from . import types, log
nutils-adapter |   File "/home/[secure]/nutils/nutils/log.py", line 26, in <module>
nutils-adapter |     import builtins, itertools, treelog, contextlib, sys, inspect, distutils
nutils-adapter |   File "/home/[secure]/.local/lib/python3.5/site-packages/treelog/__init__.py", line 25, in <module>
nutils-adapter |     from . import iter, proto
nutils-adapter |   File "/home/[secure]/.local/lib/python3.5/site-packages/treelog/iter.py", line 16, in <module>
nutils-adapter |     class wrap(typing.Generic[T]):
nutils-adapter |   File "/home/[secure]/.local/lib/python3.5/site-packages/treelog/iter.py", line 49, in wrap
nutils-adapter |     def __exit__(self, exctype: typing.Optional[typing.Type[BaseException]], excvalue: typing.Optional[BaseException], tb: typing.Optional[types.TracebackType]) -> None:
nutils-adapter |   File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
nutils-adapter |     return Union[arg, type(None)]
nutils-adapter |   File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
nutils-adapter |     dict(self.__dict__), parameters, _root=True)
nutils-adapter |   File "/usr/lib/python3.5/typing.py", line 512, in __new__
nutils-adapter |     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
nutils-adapter |   File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
nutils-adapter |     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
nutils-adapter |   File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
nutils-adapter |     if super().__subclasscheck__(cls):
nutils-adapter |   File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
nutils-adapter |     for scls in cls.__subclasses__():
nutils-adapter | TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```
Following this message, the OpenFOAM participant fails to communicate with the crashed Nutils participant and terminates the test.

**Comment by Eder-K** [comment]
This was fixed on the systemtests side as a result of the merging of https://github.com/precice/systemtests/pull/132.
